### ISSUE TITLE
MAVLINK_DIALECT changed for libmavconn.

### ISSUE THREAD

**Issue by AlexisTM** [UAVenture/ros-setups#8]
The dialect pixhawk do no more exist. It has to be replaced by common.

https://github.com/UAVenture/ros-setups/blob/master/intel-edison/install_ros.sh#L75

**Comment by AndreasAntener** [comment]
That is true, thanks for mentioning it. Did you recently use the script and does it still work otherwise?

**Comment by AlexisTM** [comment]
I am currently using and having issues. 

Current issue; Version of boost needed is now 1_53_0 (for roscpp to compile) instead of 1_49_0 from the repos because the API changed the  BOOST_SCOPE_EXIT macro.

But some parts has to be built :           
* boost_signals
* boost_filesystem
* boost_system

**Comment by AlexisTM** [comment]
Boost 1.58.0 built completely, I saved the whole directory and I can share it to anyone who need. (I do not know which part of boost is used, so I just built the whole Boost library, Static & Shared Object libraries.

The compilation boost compilation (and removing the old 1_49_0 libboost) 

```
sudo apt-get remove libboost-dev
sudo apt-get autoremove
wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz ~/ros_catkin_ws/external_src/
mkdir ~/ros_catkin_ws/external_src/boost
cd ~/ros_catkin_ws/external_src/boost
tar -xf ~/ros_catkin_ws/external_src/boost_1_58_0.tar.gz --exclude='doc'
cd ~/ros_catkin_ws/external_src/boost/boost_1_58_0
./bootstrap.sh # makes b2 executable
./b2
# This takes a very very very long time on the Edison. (Wanted to crosscompile, but I got b2 in the way)
# Saved the boost_1_58_0 folder here, but the libraries (boost_1_58_0/stage/lib/boost_.so) are no more symlinks to the actual library (boost_1_58_0/stage/lib/boost_.so.1.58.0)
# Prefix chosen is /usr as the boost library we can install from apt-get is installed with that prefix.
sudo ./b2 install --prefix=/usr/
```

**Comment by AlexisTM** [comment]
Build successful, with the right version of boost. Thanks a lot for your script. :smile: 

I wonder why do you source the devel package, as the package is already installed and sourced in /home/ros.

```
echo "source /home/ros/indigo/setup.bash" >> ~/.profile
source ~/.profile

echo "source ~/ros_catkin_ws/devel_isolated/setup.bash" >> ~/.bashrc
source ~/.bashrc
```

Isn't it the same packages?

**Comment by AndreasAntener** [comment]
Glad to hear. Would you mind making a pull request with your changes to the script?

As far as I remember you'll source first the ROS installation, and then the workspace built packages.

**Comment by AlexisTM** [comment]
Outdated.
